//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Script
{
    using System;
    using System.Xml;
    using System.Xml.Schema;
    using System.Collections.Generic;
    using HP.ST.Fwk.RunTimeFWK;
    using HP.ST.Fwk.RunTimeFWK.CheckpointFWK;
    using HP.ST.Fwk.RunTimeFWK.Utilities;
    using HP.ST.Ext.CheckpointLogicOperators;
    using HP.ST.Ext.BindingImpl.Getters;
    using HP.ST.Ext.BindingImpl.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Getters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.Setters;
    using HP.ST.Fwk.RunTimeFWK.BindingFWK.PropInfo;
    using HP.ST.Ext.CheckpointRules;
    using HP.ST.Ext.CheckpointRules.ArrayCheckpoints;
    
    
    public partial class WorkFlowScript
    {
        
        private void set_StServiceCallActivity7_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?><xs:schema xmlns=\"http://schemas.xmlsoap.o" +
                    "rg/soap/envelope/\" xmlns:vtd=\"hp.visual_test_designer\" elementFormDefault=\"quali" +
                    "fied\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xs=\"http" +
                    "://www.w3.org/2001/XMLSchema\"><xs:import schemaLocation=\"EmbeddedResources/Membe" +
                    "rAcco\\webServices\\MemberAcco\\_4.xsd\" namespace=\"http://hp.com/SOAQ/ServiceSimula" +
                    "tion/2010/demo/01/Imports\" /><xs:attribute name=\"fullName\" type=\"xs:string\" /><x" +
                    "s:attribute name=\"group\" type=\"xs:string\" /><xs:attribute name=\"serialize\" type=" +
                    "\"xs:string\" /><xs:attribute name=\"argType\" type=\"xs:string\" /><xs:element name=\"" +
                    "Envelope\" type=\"Envelope\" /><xs:complexType name=\"Envelope\"><xs:sequence><xs:ele" +
                    "ment minOccurs=\"0\" ref=\"Header\" /><xs:element minOccurs=\"1\" ref=\"Body\" /></xs:se" +
                    "quence><xs:anyAttribute processContents=\"lax\" /></xs:complexType><xs:element nam" +
                    "e=\"Header\" type=\"Header\" /><xs:complexType name=\"Header\"><xs:sequence xmlns=\"\"><" +
                    "xs:any minOccurs=\"0\" maxOccurs=\"unbounded\" processContents=\"lax\" /></xs:sequence" +
                    "><xs:anyAttribute processContents=\"lax\" /></xs:complexType><xs:element name=\"Bod" +
                    "y\" type=\"Body\" /><xs:complexType name=\"Body\"><xs:sequence xmlns=\"\"><xs:element x" +
                    "mlns:q1=\"http://hp.com/SOAQ/ServiceSimulation/2010/demo/01\" ref=\"q1:memberSearch" +
                    "Response\" /></xs:sequence><xs:anyAttribute namespace=\"##any\" processContents=\"la" +
                    "x\"><xs:annotation><xs:documentation>Prose in the spec does not specify that attr" +
                    "ibutes are allowed on the Body element</xs:documentation></xs:annotation></xs:an" +
                    "yAttribute></xs:complexType><xs:attribute name=\"mustUnderstand\"><xs:simpleType><" +
                    "xs:restriction base=\"xs:boolean\"><xs:pattern value=\"0|1\" /></xs:restriction></xs" +
                    ":simpleType></xs:attribute><xs:attribute name=\"actor\" type=\"xs:anyURI\" /><xs:sim" +
                    "pleType name=\"encodingStyle\"><xs:annotation><xs:documentation>\'encodingStyle\' in" +
                    "dicates any canonicalization conventions followed in the contents of the contain" +
                    "ing element.  For example, the value \'http://schemas.xmlsoap.org/soap/encoding/\'" +
                    " indicates the pattern described in SOAP specification</xs:documentation></xs:an" +
                    "notation><xs:list itemType=\"xs:anyURI\" /></xs:simpleType><xs:attribute name=\"enc" +
                    "odingStyle\" type=\"encodingStyle\" /><xs:attributeGroup name=\"encodingStyle\"><xs:a" +
                    "ttribute ref=\"encodingStyle\" /></xs:attributeGroup><xs:element name=\"Fault\" type" +
                    "=\"Fault\" /><xs:complexType name=\"Fault\" final=\"extension\"><xs:annotation><xs:doc" +
                    "umentation>Fault reporting structure</xs:documentation></xs:annotation><xs:seque" +
                    "nce><xs:element name=\"faultcode\" type=\"xs:QName\" /><xs:element name=\"faultstring" +
                    "\" type=\"xs:string\" /><xs:element minOccurs=\"0\" name=\"faultactor\" type=\"xs:anyURI" +
                    "\" /><xs:element minOccurs=\"0\" name=\"detail\" type=\"detail\" /></xs:sequence></xs:c" +
                    "omplexType><xs:complexType name=\"detail\"><xs:sequence><xs:any minOccurs=\"0\" maxO" +
                    "ccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\" /></xs:sequence><xs:an" +
                    "yAttribute namespace=\"##any\" processContents=\"lax\" /></xs:complexType></xs:schem" +
                    "a>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

        }
        
        private void set_StServiceCallActivity6_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?><xs:schema xmlns=\"http://schemas.xmlsoap.o" +
                    "rg/soap/envelope/\" xmlns:vtd=\"hp.visual_test_designer\" elementFormDefault=\"quali" +
                    "fied\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xs=\"http" +
                    "://www.w3.org/2001/XMLSchema\"><xs:import schemaLocation=\"EmbeddedResources/Membe" +
                    "rAcco\\webServices\\MemberAcco\\_4.xsd\" namespace=\"http://hp.com/SOAQ/ServiceSimula" +
                    "tion/2010/demo/01/Imports\" /><xs:attribute name=\"fullName\" type=\"xs:string\" /><x" +
                    "s:attribute name=\"group\" type=\"xs:string\" /><xs:attribute name=\"serialize\" type=" +
                    "\"xs:string\" /><xs:attribute name=\"argType\" type=\"xs:string\" /><xs:element name=\"" +
                    "Envelope\" type=\"Envelope\" /><xs:complexType name=\"Envelope\"><xs:sequence><xs:ele" +
                    "ment minOccurs=\"0\" ref=\"Header\" /><xs:element minOccurs=\"1\" ref=\"Body\" /></xs:se" +
                    "quence><xs:anyAttribute processContents=\"lax\" /></xs:complexType><xs:element nam" +
                    "e=\"Header\" type=\"Header\" /><xs:complexType name=\"Header\"><xs:sequence xmlns=\"\"><" +
                    "xs:any minOccurs=\"0\" maxOccurs=\"unbounded\" processContents=\"lax\" /></xs:sequence" +
                    "><xs:anyAttribute processContents=\"lax\" /></xs:complexType><xs:element name=\"Bod" +
                    "y\" type=\"Body\" /><xs:complexType name=\"Body\"><xs:sequence xmlns=\"\"><xs:element x" +
                    "mlns:q1=\"http://hp.com/SOAQ/ServiceSimulation/2010/demo/01\" ref=\"q1:getMemberPla" +
                    "nResponse\" /></xs:sequence><xs:anyAttribute namespace=\"##any\" processContents=\"l" +
                    "ax\"><xs:annotation><xs:documentation>Prose in the spec does not specify that att" +
                    "ributes are allowed on the Body element</xs:documentation></xs:annotation></xs:a" +
                    "nyAttribute></xs:complexType><xs:attribute name=\"mustUnderstand\"><xs:simpleType>" +
                    "<xs:restriction base=\"xs:boolean\"><xs:pattern value=\"0|1\" /></xs:restriction></x" +
                    "s:simpleType></xs:attribute><xs:attribute name=\"actor\" type=\"xs:anyURI\" /><xs:si" +
                    "mpleType name=\"encodingStyle\"><xs:annotation><xs:documentation>\'encodingStyle\' i" +
                    "ndicates any canonicalization conventions followed in the contents of the contai" +
                    "ning element.  For example, the value \'http://schemas.xmlsoap.org/soap/encoding/" +
                    "\' indicates the pattern described in SOAP specification</xs:documentation></xs:a" +
                    "nnotation><xs:list itemType=\"xs:anyURI\" /></xs:simpleType><xs:attribute name=\"en" +
                    "codingStyle\" type=\"encodingStyle\" /><xs:attributeGroup name=\"encodingStyle\"><xs:" +
                    "attribute ref=\"encodingStyle\" /></xs:attributeGroup><xs:element name=\"Fault\" typ" +
                    "e=\"Fault\" /><xs:complexType name=\"Fault\" final=\"extension\"><xs:annotation><xs:do" +
                    "cumentation>Fault reporting structure</xs:documentation></xs:annotation><xs:sequ" +
                    "ence><xs:element name=\"faultcode\" type=\"xs:QName\" /><xs:element name=\"faultstrin" +
                    "g\" type=\"xs:string\" /><xs:element minOccurs=\"0\" name=\"faultactor\" type=\"xs:anyUR" +
                    "I\" /><xs:element minOccurs=\"0\" name=\"detail\" type=\"detail\" /></xs:sequence></xs:" +
                    "complexType><xs:complexType name=\"detail\"><xs:sequence><xs:any minOccurs=\"0\" max" +
                    "Occurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\" /></xs:sequence><xs:a" +
                    "nyAttribute namespace=\"##any\" processContents=\"lax\" /></xs:complexType></xs:sche" +
                    "ma>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

        }
        
        private void set_StServiceCallActivity5_checkpoints(STActivityBase activity)
        {
            VTDPropertyInfoBase stracturalOutputEnvelope = new VTDPropertyInfoBase("OutputEnvelope", "/*[local-name(.)=\'Envelope\'][1]");
            IList<VTDPropertyInfoBase> stracturalPropsInfo = new List<VTDPropertyInfoBase>();
            CpValObj ExpectedSchema = new CpValObj("<?xml version=\"1.0\" encoding=\"utf-16\"?><xs:schema xmlns=\"http://schemas.xmlsoap.o" +
                    "rg/soap/envelope/\" xmlns:vtd=\"hp.visual_test_designer\" elementFormDefault=\"quali" +
                    "fied\" targetNamespace=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xs=\"http" +
                    "://www.w3.org/2001/XMLSchema\"><xs:import schemaLocation=\"EmbeddedResources/Membe" +
                    "rAcco\\webServices\\MemberAcco\\_4.xsd\" namespace=\"http://hp.com/SOAQ/ServiceSimula" +
                    "tion/2010/demo/01/Imports\" /><xs:attribute name=\"fullName\" type=\"xs:string\" /><x" +
                    "s:attribute name=\"group\" type=\"xs:string\" /><xs:attribute name=\"serialize\" type=" +
                    "\"xs:string\" /><xs:attribute name=\"argType\" type=\"xs:string\" /><xs:element name=\"" +
                    "Envelope\" type=\"Envelope\" /><xs:complexType name=\"Envelope\"><xs:sequence><xs:ele" +
                    "ment minOccurs=\"0\" ref=\"Header\" /><xs:element minOccurs=\"1\" ref=\"Body\" /></xs:se" +
                    "quence><xs:anyAttribute processContents=\"lax\" /></xs:complexType><xs:element nam" +
                    "e=\"Header\" type=\"Header\" /><xs:complexType name=\"Header\"><xs:sequence xmlns=\"\"><" +
                    "xs:any minOccurs=\"0\" maxOccurs=\"unbounded\" processContents=\"lax\" /></xs:sequence" +
                    "><xs:anyAttribute processContents=\"lax\" /></xs:complexType><xs:element name=\"Bod" +
                    "y\" type=\"Body\" /><xs:complexType name=\"Body\"><xs:sequence xmlns=\"\"><xs:element x" +
                    "mlns:q1=\"http://hp.com/SOAQ/ServiceSimulation/2010/demo/01\" ref=\"q1:getMemberDet" +
                    "ailResponse\" /></xs:sequence><xs:anyAttribute namespace=\"##any\" processContents=" +
                    "\"lax\"><xs:annotation><xs:documentation>Prose in the spec does not specify that a" +
                    "ttributes are allowed on the Body element</xs:documentation></xs:annotation></xs" +
                    ":anyAttribute></xs:complexType><xs:attribute name=\"mustUnderstand\"><xs:simpleTyp" +
                    "e><xs:restriction base=\"xs:boolean\"><xs:pattern value=\"0|1\" /></xs:restriction><" +
                    "/xs:simpleType></xs:attribute><xs:attribute name=\"actor\" type=\"xs:anyURI\" /><xs:" +
                    "simpleType name=\"encodingStyle\"><xs:annotation><xs:documentation>\'encodingStyle\'" +
                    " indicates any canonicalization conventions followed in the contents of the cont" +
                    "aining element.  For example, the value \'http://schemas.xmlsoap.org/soap/encodin" +
                    "g/\' indicates the pattern described in SOAP specification</xs:documentation></xs" +
                    ":annotation><xs:list itemType=\"xs:anyURI\" /></xs:simpleType><xs:attribute name=\"" +
                    "encodingStyle\" type=\"encodingStyle\" /><xs:attributeGroup name=\"encodingStyle\"><x" +
                    "s:attribute ref=\"encodingStyle\" /></xs:attributeGroup><xs:element name=\"Fault\" t" +
                    "ype=\"Fault\" /><xs:complexType name=\"Fault\" final=\"extension\"><xs:annotation><xs:" +
                    "documentation>Fault reporting structure</xs:documentation></xs:annotation><xs:se" +
                    "quence><xs:element name=\"faultcode\" type=\"xs:QName\" /><xs:element name=\"faultstr" +
                    "ing\" type=\"xs:string\" /><xs:element minOccurs=\"0\" name=\"faultactor\" type=\"xs:any" +
                    "URI\" /><xs:element minOccurs=\"0\" name=\"detail\" type=\"detail\" /></xs:sequence></x" +
                    "s:complexType><xs:complexType name=\"detail\"><xs:sequence><xs:any minOccurs=\"0\" m" +
                    "axOccurs=\"unbounded\" namespace=\"##any\" processContents=\"lax\" /></xs:sequence><xs" +
                    ":anyAttribute namespace=\"##any\" processContents=\"lax\" /></xs:complexType></xs:sc" +
                    "hema>", XmlTypeCode.None);
            stracturalPropsInfo.Add(stracturalOutputEnvelope);
            BaseCPRule StracturalRule = new StracturalRule(activity, ExpectedSchema, stracturalPropsInfo);
            activity.AddCheckpointRule(StracturalRule);

        }
    }
}
