//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.SOAQ.ServiceSimulation.Demo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApprovalResult", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public enum ApprovalResult : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        denied = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        approved = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", ConfigurationName="IApproval", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface IApproval
{
    
    // CODEGEN: Generating message contract since the wrapper name (ProcedureRequest) of message ProcedureRequest does not match the default value (approveProcedure)
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IApproval/approveProcedure", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IApproval/approveProcedureRespo" +
        "nse")]
    ApprovalResponse approveProcedure(ProcedureRequest request);
    
    // CODEGEN: Generating message contract since the wrapper name (PaymentRequest) of message PaymentRequest does not match the default value (approvePayment)
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IApproval/approvePayment", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IApproval/approvePaymentRespons" +
        "e")]
    ApprovalResponse approvePayment(PaymentRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ProcedureRequest", WrapperNamespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", IsWrapped=true)]
public partial class ProcedureRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01")]
    public long memberId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=0)]
    public float amount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=1)]
    public long claimId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=2)]
    public HP.SOAQ.ServiceSimulation.Demo.Customer customer;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=3)]
    public HP.SOAQ.ServiceSimulation.Demo.MedicalHistory medicalHistory;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=4)]
    public string procedure;
    
    public ProcedureRequest()
    {
    }
    
    public ProcedureRequest(long memberId, float amount, long claimId, HP.SOAQ.ServiceSimulation.Demo.Customer customer, HP.SOAQ.ServiceSimulation.Demo.MedicalHistory medicalHistory, string procedure)
    {
        this.memberId = memberId;
        this.amount = amount;
        this.claimId = claimId;
        this.customer = customer;
        this.medicalHistory = medicalHistory;
        this.procedure = procedure;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="ApprovalResponse", WrapperNamespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", IsWrapped=true)]
public partial class ApprovalResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=0)]
    public string description;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=1)]
    public HP.SOAQ.ServiceSimulation.Demo.ApprovalResult result;
    
    public ApprovalResponse()
    {
    }
    
    public ApprovalResponse(string description, HP.SOAQ.ServiceSimulation.Demo.ApprovalResult result)
    {
        this.description = description;
        this.result = result;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PaymentRequest", WrapperNamespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", IsWrapped=true)]
public partial class PaymentRequest
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01")]
    public long memberId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=0)]
    public float amount;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=1)]
    public long claimId;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", Order=2)]
    public HP.SOAQ.ServiceSimulation.Demo.Customer customer;
    
    public PaymentRequest()
    {
    }
    
    public PaymentRequest(long memberId, float amount, long claimId, HP.SOAQ.ServiceSimulation.Demo.Customer customer)
    {
        this.memberId = memberId;
        this.amount = amount;
        this.claimId = claimId;
        this.customer = customer;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IApprovalChannel : IApproval, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ApprovalClient : System.ServiceModel.ClientBase<IApproval>, IApproval
{
    
    public ApprovalClient()
    {
    }
    
    public ApprovalClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ApprovalClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ApprovalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ApprovalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ApprovalResponse IApproval.approveProcedure(ProcedureRequest request)
    {
        return base.Channel.approveProcedure(request);
    }
    
    public string approveProcedure(long memberId, float amount, long claimId, HP.SOAQ.ServiceSimulation.Demo.Customer customer, HP.SOAQ.ServiceSimulation.Demo.MedicalHistory medicalHistory, string procedure, out HP.SOAQ.ServiceSimulation.Demo.ApprovalResult result)
    {
        ProcedureRequest inValue = new ProcedureRequest();
        inValue.memberId = memberId;
        inValue.amount = amount;
        inValue.claimId = claimId;
        inValue.customer = customer;
        inValue.medicalHistory = medicalHistory;
        inValue.procedure = procedure;
        ApprovalResponse retVal = ((IApproval)(this)).approveProcedure(inValue);
        result = retVal.result;
        return retVal.description;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ApprovalResponse IApproval.approvePayment(PaymentRequest request)
    {
        return base.Channel.approvePayment(request);
    }
    
    public string approvePayment(long memberId, float amount, long claimId, HP.SOAQ.ServiceSimulation.Demo.Customer customer, out HP.SOAQ.ServiceSimulation.Demo.ApprovalResult result)
    {
        PaymentRequest inValue = new PaymentRequest();
        inValue.memberId = memberId;
        inValue.amount = amount;
        inValue.claimId = claimId;
        inValue.customer = customer;
        ApprovalResponse retVal = ((IApproval)(this)).approvePayment(inValue);
        result = retVal.result;
        return retVal.description;
    }
}
