//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.SOAQ.ServiceSimulation.Demo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurrencyPair", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class CurrencyPair : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Currency fromField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Currency toField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Currency from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Currency to
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", ConfigurationName="IExchangeRate", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface IExchangeRate
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IExchangeRate/getNoonRate", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IExchangeRate/getNoonRateRespon" +
        "se")]
    float getNoonRate(HP.SOAQ.ServiceSimulation.Demo.CurrencyPair currencies);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IExchangeRate/getHistoricalNoon" +
        "Rate", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IExchangeRate/getHistoricalNoon" +
        "RateResponse")]
    float getHistoricalNoonRate(HP.SOAQ.ServiceSimulation.Demo.CurrencyPair currencies, System.DateTime date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IExchangeRate/getCurrentRate", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IExchangeRate/getCurrentRateRes" +
        "ponse")]
    float getCurrentRate(HP.SOAQ.ServiceSimulation.Demo.CurrencyPair currencies);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IExchangeRateChannel : IExchangeRate, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ExchangeRateClient : System.ServiceModel.ClientBase<IExchangeRate>, IExchangeRate
{
    
    public ExchangeRateClient()
    {
    }
    
    public ExchangeRateClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ExchangeRateClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ExchangeRateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ExchangeRateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public float getNoonRate(HP.SOAQ.ServiceSimulation.Demo.CurrencyPair currencies)
    {
        return base.Channel.getNoonRate(currencies);
    }
    
    public float getHistoricalNoonRate(HP.SOAQ.ServiceSimulation.Demo.CurrencyPair currencies, System.DateTime date)
    {
        return base.Channel.getHistoricalNoonRate(currencies, date);
    }
    
    public float getCurrentRate(HP.SOAQ.ServiceSimulation.Demo.CurrencyPair currencies)
    {
        return base.Channel.getCurrentRate(currencies);
    }
}
