//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.SOAQ.ServiceSimulation.Demo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShortName", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.SOAQ.ServiceSimulation.Demo.Name))]
    public partial class ShortName : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Name", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Name : HP.SOAQ.ServiceSimulation.Demo.ShortName
    {
        
        private string middleNameField;
        
        private string prefixField;
        
        private string suffixField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string suffix
        {
            get
            {
                return this.suffixField;
            }
            set
            {
                this.suffixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long householdIdField;
        
        private long memberIdField;
        
        private string socialSecurityNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long householdId
        {
            get
            {
                return this.householdIdField;
            }
            set
            {
                this.householdIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long memberId
        {
            get
            {
                return this.memberIdField;
            }
            set
            {
                this.memberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string socialSecurityNumber
        {
            get
            {
                return this.socialSecurityNumberField;
            }
            set
            {
                this.socialSecurityNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plan", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Plan : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private float approvalLimitField;
        
        private long idField;
        
        private string nameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float approvalLimit
        {
            get
            {
                return this.approvalLimitField;
            }
            set
            {
                this.approvalLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Detail", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Detail : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Address addressField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Currency currencyField;
        
        private long householdIdField;
        
        private long memberIdField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Person personField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Phone phoneField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Address address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Currency currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long householdId
        {
            get
            {
                return this.householdIdField;
            }
            set
            {
                this.householdIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long memberId
        {
            get
            {
                return this.memberIdField;
            }
            set
            {
                this.memberIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Person person
        {
            get
            {
                return this.personField;
            }
            set
            {
                this.personField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Phone phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cityField;
        
        private string countryField;
        
        private System.DateTime endDateField;
        
        private string line1Field;
        
        private string line2Field;
        
        private System.DateTime startDateField;
        
        private string stateField;
        
        private string zipField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime dateOfBirthField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Gender genderField;
        
        private HP.SOAQ.ServiceSimulation.Demo.Name nameField;
        
        private string socialSecurityNumberField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Gender gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.Name name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string socialSecurityNumber
        {
            get
            {
                return this.socialSecurityNumberField;
            }
            set
            {
                this.socialSecurityNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phone", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public partial class Phone : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string extensionField;
        
        private string phoneNumberField;
        
        private HP.SOAQ.ServiceSimulation.Demo.PhoneNumberType phoneNumberTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.SOAQ.ServiceSimulation.Demo.PhoneNumberType phoneNumberType
        {
            get
            {
                return this.phoneNumberTypeField;
            }
            set
            {
                this.phoneNumberTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public enum Gender : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MALE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FEMALE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNKNOWN = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneNumberType", Namespace="http://schemas.datacontract.org/2004/07/HP.SOAQ.ServiceSimulation.Demo")]
    public enum PhoneNumberType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DAY = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EVENING = 1,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01", ConfigurationName="IMemberAccounts", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
public interface IMemberAccounts
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/memberSearch", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/memberSearchRes" +
        "ponse")]
    HP.SOAQ.ServiceSimulation.Demo.Member[] memberSearch(HP.SOAQ.ServiceSimulation.Demo.ShortName name, System.DateTime dateOfBirth, string socialSecurityNumber, string zipCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/getMemberPlan", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/getMemberPlanRe" +
        "sponse")]
    HP.SOAQ.ServiceSimulation.Demo.Plan getMemberPlan(long memberId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/getMemberDetail" +
        "", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/getMemberDetail" +
        "Response")]
    HP.SOAQ.ServiceSimulation.Demo.Detail getMemberDetail(long memberId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/getMemberMedica" +
        "lHistory", ReplyAction="http://hp.com/SOAQ/ServiceSimulation/2010/demo/01/IMemberAccounts/getMemberMedica" +
        "lHistoryResponse")]
    HP.SOAQ.ServiceSimulation.Demo.MedicalHistory getMemberMedicalHistory(long memberId);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMemberAccountsChannel : IMemberAccounts, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MemberAccountsClient : System.ServiceModel.ClientBase<IMemberAccounts>, IMemberAccounts
{
    
    public MemberAccountsClient()
    {
    }
    
    public MemberAccountsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MemberAccountsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MemberAccountsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MemberAccountsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public HP.SOAQ.ServiceSimulation.Demo.Member[] memberSearch(HP.SOAQ.ServiceSimulation.Demo.ShortName name, System.DateTime dateOfBirth, string socialSecurityNumber, string zipCode)
    {
        return base.Channel.memberSearch(name, dateOfBirth, socialSecurityNumber, zipCode);
    }
    
    public HP.SOAQ.ServiceSimulation.Demo.Plan getMemberPlan(long memberId)
    {
        return base.Channel.getMemberPlan(memberId);
    }
    
    public HP.SOAQ.ServiceSimulation.Demo.Detail getMemberDetail(long memberId)
    {
        return base.Channel.getMemberDetail(memberId);
    }
    
    public HP.SOAQ.ServiceSimulation.Demo.MedicalHistory getMemberMedicalHistory(long memberId)
    {
        return base.Channel.getMemberMedicalHistory(memberId);
    }
}
